apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeScheduleConfiguration
Profiles:
  - scheduleName: my-scheduler
leaderElection:
  leaderElect: false

kubectl create configmap my-scheduler-config --from-file=myscheduler-config.yaml -n kube-system


apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp
data:
  key: value


