
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: devuser-developer-binding
subjects:
  - kind: user
    name: dev-user
    apiGroups: rbac.authorization.k8s.io
roleRef:
  - kind: Role
    name: developer
    apiGroups: rbac.authorization.k8s.io



