apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  db_host: mysql
  db_user: root
  db_password: passwd@123!

### convert data from plain text to encoded

echo -n 'mysql' | base64
echo -n 'root' | base64
echo -n 'passwd@123!' | base64

Add these values to the definition file

### create a secret & add the secret name in secretRef so pod can pick
apiVersion: v1 
kind: Pod 
metadata:
  labels:
    name: webapp-pod
  name: webapp-pod
  namespace: default 
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    imagePullPolicy: Always
    name: webapp
    envFrom:
    - secretRef:
        name: db-secret