apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: static-busybox
  name: static-busybox
spec:
  containers:
  - command:
    - sleep
    - "1000"
    image: busybox
    name: static-busybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}


#### Put this file on workernode or kubelet server node inside kubernetes configuration directory
## e.g. /etc/kubernetes/manifests

command:
# kubectl run static-busybox --image busybox --command sleep 1000 --dry-run=client -o yaml > busybox.yaml
# kubectl run --restart=Never --image=busybox:1.28.4 static-busybox --dry-run=client -o yaml --command -- sleep 1000 > /etc/kubernetes/manifests/static-busybox.yaml

ps -ef | grep /usr/bin/kubelet
grep -i staticpod /var/lib/kubelet/config.yaml
remove files form location /etc/dire

