apiVersion: v1
kind: pod 
metadata:
  name: myapp-pod
  lables:
    app: myapp
spec:
  containers:
  - name: nginx
    image: nginx
    command: ["sleep","1000"]
  securityContext:
    runAsUser: 1000
  capabilities: 
    add: ["admin"]



### capabilities only support at container level not pod level


---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
  namespace: default
spec:
  containers:
    command:
    - sleep
    - "4800"
    image: ubuntu
    name: ubuntu-sleeper
    securityContext:
      capabilities:
        add: ["SYS_TIME"]